ansible-collections/google.cloud

- galaxy.yml
- plugins/doc_fragment/gcp.py
- plugins/module_utils/gcp_utils.py
- plugins/modules/gcp_bigquery_table.py
- plugins/modules/gcp_storage_object.py
> Sanity test fixes

- galaxy.yml
bumping collection version for next release as sanity test fixes were merged.
> bumping collection version

- .github/workflows/integration.yml
Runs integration tests through Github Actions
```paste below
```
> Github Action for Integration Test Running

- plugins/filter/gcp_kms_filters.py
Advertenly gcp_kms_filters was located to community.general,
moving this filter to its correct location i.e. google.cloud collection
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
plugins/filter/gcp_kms_filters.py
> Moved gcp_kms_filters to google.cloud collection

- .ansible-lint
- .github/workflows/gcsfuse.yml
- .yamllint
- molecule/gcsfuse/Dockerfile.j2
- molecule/gcsfuse/converge.yml
- molecule/gcsfuse/files/override.conf
- molecule/gcsfuse/molecule.yml
- molecule/gcsfuse/tests/test_default.py
- molecule/gcsfuse/verify.yml
Adds gcsfuse role testing using Molecule and GitHub actions
google.cloud.gcsfuse
```paste below
```
> added gcsfuse role tests for GitHub Actions

- galaxy.yml
add tags to allow better results on Ansible Galaxy
google.cloud
```paste below
```
> add tags to allow better results on Ansible Galaxy

- tests/unit/plugins/test_gcp_utils.py
Fixes #227.
CC @rambleraptor 
tests/unit/plugins/test_gcp_utils.py
> Add gcp_utils unit tests from community.general.

- .github/workflows/automationhub.yml
> automation hub upload

- galaxy.yml
> bump up release

- .changelog/3068.txt
- galaxy.yml
- molecule/gcloud/tests/test_default.py
- molecule/gcsfuse/tests/test_default.py
- roles/stackdriver_logging/molecule/default/tests/test_default.py
- roles/stackdriver_monitoring/molecule/default/tests/test_default.py
- tests/unit/plugins/test_gcp_utils.py
```paste below
```
Some misc. fixes.
> some fixes

- molecule/gcloud/tests/test_default.py
- molecule/gcsfuse/tests/test_default.py
- plugins/module_utils/gcp_utils.py
- plugins/modules/gcp_storage_object.py
- roles/stackdriver_logging/molecule/default/tests/test_default.py
- roles/stackdriver_monitoring/molecule/default/tests/test_default.py
- tests/unit/plugins/test_gcp_utils.py
> Last fixes

- .gitmodules
Rename google_cloud_ops_agents ansible role to remove hypens, Fixes #427 
google_cloud_ops_agents ansible role
> Update google_cloud_ops_agents submodule name to remove hypens

- galaxy.yml
updated 'repository' & 'issues' URLs in `galaxy.yml` (replaces #455)
- galaxy.yml Pull Request
- galaxy.yml
> updated 'repository' & 'issues' URLs in galaxy.yml

- .github/workflows/ansible-test.yml
- tests/unit/plugins/test_gcp_utils.py
As a first step to rehabilitate the google.cloud repository, adding actions to help ensure that the collection is still passing tests as changes are merged.
> Adding a GitHub action to run ansible-test

- plugins/modules/gcp_storage_object.py
While version `1.2..0` might work it does not reflect the desired requirement (`1.2.0`).
A small typo was included in a package version in `gcp_storage_object.py`'s doc.
gcp_storage_object
> Docs: fix typo in gcp_storage_object.py

- plugins/modules/gcp_compute_backend_service.py
- plugins/modules/gcp_compute_url_map.py
- tests/integration/targets/gcp_compute_backend_service/aliases
Merging #393, and using those fixes to fix the backend_service tests.
> merge #393 and enable compute_backend_service tests

- .github/workflows/ansible-integration-tests.yml
- plugins/modules/gcp_compute_url_map.py
- scripts/cleanup-project.sh
fixing compute_url_map, add cleanup script
Compute_url_map was broken by #509: It also merged in #393, which
has an erroneous understanding that compute_url_map always returns
a diff (integration tests show it does not).
Adding a cleanup script to help with environment hygiene.
Added cleanup to CI to help make tests less flakey.
> fixing compute_url_map, add cleanup script

- tests/integration/targets/gcp_compute_autoscaler/aliases
- tests/integration/targets/gcp_compute_autoscaler/tasks/autogen.yml
- tests/integration/targets/gcp_compute_disk/aliases
- tests/integration/targets/gcp_compute_global_forwarding_rule/aliases
Tests were working with only minor config tweaks
- compute_autoscaler
- compute_disk
- global_forwarding_rule
> enabling 3 more tests

- plugins/modules/gcp_compute_vpn_tunnel.py
- scripts/cleanup-project.sh
- tests/integration/targets/gcp_compute_region_target_http_proxy/aliases
- tests/integration/targets/gcp_compute_region_target_http_proxy/tasks/autogen.yml
- tests/integration/targets/gcp_compute_target_http_proxy/aliases
- tests/integration/targets/gcp_compute_target_https_proxy/aliases
- tests/integration/targets/gcp_compute_target_ssl_proxy/aliases
- tests/integration/targets/gcp_compute_target_tcp_proxy/aliases
- tests/integration/targets/gcp_compute_target_vpn_gateway/aliases
- tests/integration/targets/gcp_compute_target_vpn_gateway/tasks/autogen.yml
- tests/integration/targets/gcp_compute_vpn_tunnel/aliases
- tests/integration/targets/gcp_compute_vpn_tunnel/tasks/autogen.yml
- tests/integration/targets/gcp_iam_service_account/tasks/autogen.yml
- gcp_compute_target_http_proxy
- gcp_compute_target_https_proxy
- gcp_compute_target_ssl_proxy
- gcp_compute_target_tcp_proxy
- gcp_compute_vpn_tunnel (minor bugfix here where a diff is found when one does not exist)
- gcp_compute_region_target_http_proxy
> fix 6 more tests

- .github/workflows/ansible-integration-tests.yml
- .gitignore
- plugins/modules/gcp_bigtable_instance.py
- plugins/modules/gcp_bigtable_instance_info.py
- plugins/modules/gcp_cloudtasks_queue.py
- plugins/modules/gcp_iam_role.py
- plugins/modules/gcp_kms_crypto_key.py
- plugins/modules/gcp_spanner_database.py
- scripts/bootstrap-project.sh
- tests/integration/targets/gcp_bigtable_instance/aliases
- tests/integration/targets/gcp_bigtable_instance/tasks/autogen.yml
- tests/integration/targets/gcp_cloudtasks_queue/aliases
- tests/integration/targets/gcp_iam_role/aliases
- tests/integration/targets/gcp_iam_role/tasks/autogen.yml
- tests/integration/targets/gcp_kms_crypto_key/aliases
- tests/integration/targets/gcp_spanner_database/aliases
- tests/integration/targets/gcp_spanner_database/tasks/autogen.yml
Fixes 5 more tests, along with bugfixes for each:
- gcp_cloudtasks_queue
- gcp_kms_crypto_key
- gcp_spanner_database
- gcp_bigtable_instance
- gcp_iam_role
> fix 5 resources

- .github/workflows/automationhub.yml
The automation hub workflow was passing an incorrect API key.
> fix automation hub

- .github/workflows/ansible-test.yml
- .gitignore
- MAINTAINING.md
- plugins/inventory/gcp_compute.py
- plugins/modules/gcp_compute_backend_service.py
- plugins/modules/gcp_compute_region_url_map.py
- plugins/modules/gcp_compute_region_url_map_info.py
- plugins/modules/gcp_compute_url_map.py
- plugins/modules/gcp_compute_url_map_info.py
- plugins/modules/gcp_compute_vpn_tunnel.py
- plugins/modules/gcp_iam_role.py
- scripts/cleanup-project.sh
- test-fixtures/cloud-function-source/build-function-zip.sh
- test-fixtures/cloud-function-source/main.py
Updating the maintainers guide with updated intructions from Ansible engineers.
Fixing linting issues, and adding the linter as a GitHub workflow to ensure there are no regressions.
> fix linting and updating maintenance guide

- changelogs/changelog.yaml
- plugins/module_utils/gcp_utils.py
- plugins/modules/gcp_iam_role.py
- plugins/modules/gcp_resourcemanager_project_info.py
- scripts/cleanup-project.sh
- tests/integration/targets/gcp_iam_role/tasks/autogen.yml
gcp_iam_role was not updating previously. The API uses a PATCH and not a PUT.
Also fixing an accidental leftover diff from a bad merge.
fixes #236.
> fix gcp_iam_role not updating

- CHANGELOG.rst
- changelogs/changelog.yaml
Updating changelong and dates to match 1.1.0 release.
> release 1.1.0

- plugins/module_utils/gcp_utils.py
- tests/unit/plugins/test_gcp_utils.py
> Fixes GcpRequest comparison for boolean parameters

- plugins/modules/gcp_storage_object.py
The `dest` field is required for upload and delete. This was not explicitly documented nor asserted.
Fixes #235.
> gcp_storage_object asserts for dest on upload

- tests/integration/targets/gcp_compute_route/tasks/autogen.yml
validating the update of a route works as per concerns raised in #542
> tests: updating the route test

- plugins/doc_fragments/gcp.py
Fix doc_fragments/gcp.py env var name
doc_fragments/gpc.py
```paste below
```
> Fix doc_fragments/gcp.py env var name

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- galaxy.yml
- meta/runtime.yml
Updates changelog and adds some missing docs.
> Prepare v1.4.0 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
- plugins/filter/gcp_kms_filters.py
- plugins/modules/gcp_secret_manager.py
This addresses a couple of issues encountered when pushing a new Galaxy release.
> Prepare a v1.4.1 release

- changelogs/gcp_pubsub_subscription_bugfix.yaml
- plugins/modules/gcp_pubsub_subscription.py
> https://github.com/ansible-collections/google.cloud/issues/653

- tests/integration/targets/gcp_pubsub_subscription/tasks/autogen.yml
> Add a test that updates a pubsub subscription

- README.md
This PR is purely a doc change to meet the [requirements for certified collections](https://access.redhat.com/articles/7068606).
> Update README to match current requirements

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
Cutting a new patch release to pick up the expanded README.
> Prepare for 1.5.3 release

- plugins/lookup/gcp_secret_manager.py
- plugins/modules/gcp_secret_manager.py
- tests/integration/targets/gcp_secret_manager/aliases
- tests/integration/targets/gcp_secret_manager/defaults/main.yml
- tests/integration/targets/gcp_secret_manager/tasks/main.yml
- tests/integration/targets/gcp_secret_manager/tasks/regionalsecrets.yml
- tests/integration/targets/gcp_secret_manager/tasks/regionalsecretslookup.yml
- tests/integration/targets/gcp_secret_manager/tasks/secrets.yml
- tests/integration/targets/gcp_secret_manager/tasks/secretslookup.yml
I've updated the Secret Manager module and lookup to support regional Secret Manager.
gcp_secret_manager
> feat(secretmanager): added support for regional secret manager

- .github/workflows/stale.yaml
For now it is in debug mode so it will just log what it would do.
> Add a workflow that closes stale issues and PRs
