ansible-collections/google.cloud

plugins/doc_fragment/gcp.py

fix for sanity test 
```ERROR: Found 1 pep8 issue(s) which need to be resolved:
ERROR: plugins/doc_fragment/gcp.py:10:1: E302: expected 2 blank lines, found 1
```
tested and passed with this fix

fixing pep8 sanity test doc fragments file

---

plugins/module_utils/gcp_utils.py

fix addressing 
```
ERROR: plugins/module_utils/gcp_utils.py:0:0: missing: __metaclass__ = type
```
tested locally and passes

fixing for sanity test metaclass

---

plugins/inventory/gcp_compute.py

Collections do not work without this.
gcp_compute inventory plugin
If you use `google.cloud.gcp_compute` in your inventory file today you get:
> plugin: Incorrect plugin name in file: google.cloud.gcp_compute
If you leave it as-is, and use just `gcp_compute`, then it will use the inventory plugin in Ansible core, which will be removed soon.

Use fully-qualified name in inventory plugin

---

galaxy.yml

Adding cloud tag to collection so that when uploaded to AH and galaxy, when searched or selected (see AH quick nav buttons) it will show up.
galaxy.yml
Adding this creates a better UX for net new users who are looking more generically for "cloud" based collections, rather than having them sift through and find it manually, we have setup buttons on the left for quick navigation for specific use cases, cloud being one. 
```paste below
```

adding tag to collection

---

roles/stackdriver_monitoring/README.md
roles/stackdriver_monitoring/defaults/main.yml
roles/stackdriver_monitoring/handlers/main.yml
roles/stackdriver_monitoring/meta/main.yml
roles/stackdriver_monitoring/molecule/default/.ansible-lint
roles/stackdriver_monitoring/molecule/default/.yamllint
roles/stackdriver_monitoring/molecule/default/Dockerfile.j2
roles/stackdriver_monitoring/molecule/default/molecule.yml
roles/stackdriver_monitoring/molecule/default/playbook.yml
roles/stackdriver_monitoring/molecule/default/tests/test_default.py
roles/stackdriver_monitoring/tasks/debian.yml
roles/stackdriver_monitoring/tasks/main.yml
roles/stackdriver_monitoring/tasks/redhat.yml
roles/stackdriver_monitoring/templates/default/stackdriver-agent
roles/stackdriver_monitoring/vars/main.yml

Provide a role for GCP Stackdriver Monitoring based on https://cloud.google.com/monitoring/agent/install-agent
google.cloud.stackdriver_monitoring
```yaml
- hosts: localhost
become: yes
tasks:
- include_role:
name: google.cloud.stackdriver_monitoring
```

Stackdriver Monitoring role for GCP Stackdriver

---

roles/gcsfuse/README.md
roles/gcsfuse/defaults/main.yml
roles/gcsfuse/handlers/main.yml
roles/gcsfuse/tasks/debian.yml
roles/gcsfuse/tasks/main.yml
roles/gcsfuse/vars/main.yml

Adding role for gcsfuse as described here https://github.com/GoogleCloudPlatform/gcsfuse
google.cloud.gcsfuse
```yaml
- hosts: servers
tasks:
- include_role:
name: google.cloud.gcsfuse
```

gcsfuse role for GCP Storage mounting

---

roles/stackdriver_logging/README.md
roles/stackdriver_logging/defaults/main.yml
roles/stackdriver_logging/handlers/main.yml
roles/stackdriver_logging/meta/main.yml
roles/stackdriver_logging/molecule/default/.ansible-lint
roles/stackdriver_logging/molecule/default/.yamllint
roles/stackdriver_logging/molecule/default/Dockerfile.j2
roles/stackdriver_logging/molecule/default/molecule.yml
roles/stackdriver_logging/molecule/default/playbook.yml
roles/stackdriver_logging/molecule/default/tests/test_default.py
roles/stackdriver_logging/tasks/debian.yml
roles/stackdriver_logging/tasks/main.yml
roles/stackdriver_logging/tasks/redhat.yml
roles/stackdriver_logging/templates/default/google-fluentd
roles/stackdriver_logging/templates/source.conf
roles/stackdriver_logging/vars/main.yml

This provides the role for installing and configuring the Stackdriver Logging agent located here https://cloud.google.com/logging/docs/agent
google.cloud.stackdriver_logging
```yaml
- hosts: localhost
become: yes
tasks:
- include_role:
name: google.cloud.stackdriver_logging
```

Stackdriver Logging role for GCP

---

plugins/inventory/gcp_compute.py

Without this, the inventory plugin is failing with Ansible `devel` branch (ansible-base) with
```
[WARNING]:  * Failed to parse /tmp/awx_136_z4baj3i4/gcp_compute.yml with auto
plugin: No module named gcp_utils
File "/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 287, in parse_source
plugin.parse(self._inventory, self._loader, source, cache=cache)
File "/usr/lib/python2.7/site-packages/ansible/plugins/inventory/auto.py", line 50, in parse
plugin = inventory_loader.get(plugin_name)
File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 552, in get
self._module_cache[path] = self._load_module_source(name, path)
File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 530, in _load_module_source
module = …
```

Change imports to work inside collection

---

plugins/inventory/gcp_compute.py

google.cloud.gcp_compute
Fixes https://github.com/ansible-collections/google.cloud/issues/382
Before
```
$ ansible-inventory --graph
[WARNING]:  * Failed to parse /home/kroukoz/inventory/gcp.yaml with
ansible_collections.google.cloud.plugins.inventory.gcp_compute plugin: [{'message': 'Compute Engine API has not
been used in project <redacted_wrong_project_id> before or it is disabled. Enable it by visiting
self._project_disks[
https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=<redacted_wrong_project_id>  then retry. If
you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.',
'domain': 'usageLimits', 'reason': 'accessNotConfigured', 'extendedHelp': …
```

Fetch projects in folder based on projectID instead of name

---

plugins/module_utils/gcp_utils.py

The function _compare_value attempts to return if "resp_value" is not set.
The problem occurs when one of the functions sets the response value "None" as string, rather than pythonic None.
This is a fix to also exit this function on a "None" string response value.
gcp_utils via gcp_compute_instance
When I rerun Ansible on already existing instances, it fails with the following error:
```paste below
Traceback (most recent call last):
File "/Users/zachzoref/.ansible/tmp/ansible-tmp-1619365490.386965-46982-80026062348664/AnsiballZ_gcp_compute_instance.py", line 102, in <module>
_ansiballz_main()
File "/Users/zachzoref/.ansible/tmp/ansible-tmp-1619365490.386965-46982-80026062348664/AnsiballZ_gcp_compute_instance.py", line 94, in _ansiballz_main
invoke_module(zipped_mod, …
```

fix 'str' object has no attribute 'get'

---

plugins/inventory/gcp_compute.py

Bug on DOCUMENTATION  pluggin inventory gcp_compute
pluggin inventory gcp_compute
if:
plugin: google.cloud.gcp_compute
then
error
with ansible_collections.google.cloud.plugins.inventory.gcp_compute plugin: Invalid value
"google.cloud.gcp_compute" for configuration option "plugin_type: inventory plugin: ansible_collections.google.cloud.plugins.inventory.gcp_compute setting: plugin ", valid values are: ['gcp_compute']
if:
plugin: gcp_compute
error
with ansible_collections.google.cloud.plugins.inventory.gcp_compute plugin: Incorrect plugin name in file:
gcp_compute
fix DOCUMENTATION options plugin choices: ['google.cloud.gcp_compute']

fix documentation for correct work inventory plugin

---

plugins/modules/gcp_storage_object.py

Fixing issue with UTF-8 conversion in Python3 for GCS uploads (https://github.com/ansible-collections/google.cloud/issues/266)
gcp_storage_object
This bug can be resolved by simply changing gcp_storage_object.py#L254 from ...
`with open(src, "r") as file_obj:` to `with open(src, "rb") as file_obj:`
Hence, this PR. This small change ensures there's no decoding attempt (or subsequent error) by forcing the file to be read as binary via the `open` func.
This approach appears similar to `download_file`'s use of the open func at gcp_storage_object.py#L243, where it specifically is configured with the b (binary) mode specifier. Not only does this resolve the issue with uploading binary files, but the change doesn't appear to harm text uploads. Unsure though if this is a …

Fixing issue with UTF-8 conversion in Python3 for GCS uploads

---

plugins/modules/gcp_sql_instance.py
plugins/modules/gcp_sql_instance_info.py

Adding customized private network configuration for cloud sql instance creation
gcp_sql_instance
Current sql instance creation has no option to set private network as Google's API allows to (check at https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances#IpConfiguration)

added private network to cloudsql instance creation

---

plugins/modules/gcp_storage_object.py

This removes a bogus parameter from the example given within the gcp_storage_object module to download an object from a GCS bucket.
gcp_storage_object
Within the example linked below, note that it states to use the `state` parameter.
https://github.com/ansible-collections/google.cloud/blob/0cd64a4a68b7d4393c97b801e3f24e6b63882294/plugins/modules/gcp_storage_object.py#L108
Yet the module also states that the `state` parameter is not valid amongst all of the listed parameters.
https://github.com/ansible-collections/google.cloud/blob/0cd64a4a68b7d4393c97b801e3f24e6b63882294/plugins/modules/gcp_storage_object.py#L32

docs: remove state param in gcp_storage_object example

---

.gitignore
CONTRIBUTING.md
tests/integration/targets/gcp_compute_region_disk/aliases
tests/integration/targets/gcp_compute_region_disk/tasks/autogen.yml

As a step toward adding integration testing into
the CI process for this project, adding instructions
on how to run the tests.
compute_region_disk was used as a test. Fixed
the tests which was previously hard-coded to
the `graphite-playground` GCP project to work
with the project in the user-configure .ini file.

Add integration test instructions

---

.github/workflows/ansible-integration-tests.yml
CONTRIBUTING.md
MAINTAINING.md

To help catch issues from PRs that would regress behavior, adding a GitHub action similar to unit tests to run integration tests.
Adding some basic instructions for future maintainers.

Adding integration tests on PRs

---

galaxy.yml

The previous URL properly redirects to the new one but let's put the updated one.

Update repository URL in galaxy.yml

---

plugins/modules/gcp_storage_object.py

The example contained the non-existent "status" parameter which causes an error with the latest release.
This PR updates the example provided in the documentation for the gcp_storage_object module. The parameter `status` does no longer exist and if used causes an error. 
Therefore it should also be removed from the example code.
`gcp_storage_object.py`
Behaviour is unchanged.

Updating gcp_storage_object module example

---

plugins/modules/gcp_compute_instance.py

Nothing major, just a link off to the google cloud site (https://cloud.google.com/compute/docs/machine-types) that has the valid machine types required for gcp_compute_instance machineType field. Make it a bit easier when perusing the docs to figure out what exactly is supposed to go in there.
gcp_compute_instance

Added in link to where machineTypes are defined

---

plugins/modules/gcp_compute_instance.py
tests/integration/targets/gcp_compute_autoscaler/tasks/autogen.yml
tests/integration/targets/gcp_compute_instance/aliases
tests/integration/targets/gcp_compute_instance/tasks/autogen.yml
tests/integration/targets/gcp_compute_instance_group/aliases
tests/integration/targets/gcp_compute_instance_group/tasks/autogen.yml
tests/integration/targets/gcp_compute_instance_group_manager/aliases
tests/integration/targets/gcp_compute_instance_group_manager/tasks/autogen.yml
tests/integration/targets/gcp_compute_instance_template/aliases
tests/integration/targets/gcp_compute_instance_template/tasks/autogen.yml
tests/integration/targets/gcp_compute_region_autoscaler/aliases
tests/integration/targets/gcp_compute_region_autoscaler/tasks/autogen.yml
tests/integration/targets/gcp_compute_region_instance_group_manager/aliases
tests/integration/targets/gcp_compute_region_instance_group_manager/tasks/autogen.yml
tests/integration/targets/gcp_compute_target_instance/aliases
tests/integration/targets/gcp_compute_target_instance/tasks/autogen.yml
tests/integration/targets/gcp_compute_target_pool/aliases

compute selflinks return back `wwww.googleapis.com` as the domain, which was causing a perma-diff. Fixing google.cloud's normalization fixes that.
Fixing the following tests as well, since creating an instance now works:
- gcp_compute_instance
- gcp_compute_instance_group
- gcp_compute_instance_group_manager
- gcp_compute_instance_template
- gcp_compute_region_autoscaler
- gcp_compute_region_instance_group_manager
- gcp_compute_target_instance
- gcp_compute_target_pool

fix compute instance + several tests

---

plugins/modules/gcp_container_cluster.py
tests/integration/targets/gcp_container_cluster/aliases
tests/integration/targets/gcp_container_cluster/tasks/autogen.yml
tests/integration/targets/gcp_container_node_pool/aliases

Incorporating a fix for GKE 1.19+ (See #444).
Inlined:
Google has removed basic-auth method from within GKE starting version 1.19 This lead the output response of the backend API not to provide basic-auth data (username and password) anymore.
The current implementation of gcp_container_cluster when generating the kubectl config file, always set basic-auth data w/o checking if there actually are available or explicitly provided even when the value are not set/provided from gcp_container_cluster.
In addition, re-enabling some tests that #444 fixed.
Co-authored-by: Xavier Lamien <laxathom@lxtnow.net>
```paste below
```

fix: gcp_container_cluster for GKE 1.19+

---

plugins/inventory/gcp_compute.py

While working with GCP inventory our team ran into a problem - inventory returns hostnames without FQDN which means we need to go through various hacks in our playbook inventories instead of using inventory_hostname as intended. This was particularly annoying when trying to configure multi-component deployments which refer to each other by inventory hostnames which need to be FQDN.
I've added a simple option (does nothing by default) that appends a custom domain suffix to all returned hosts which is sufficient for our needs as we use single base domain suffix per environment.
Having this really simplified dealing with GCP inventory and, being entirely optional and disabled by default, shouldn't have any side-effects. Would really appreciate this being reviewed and merged. Thanks in …

Add custom domain suffix option (base_domain)

---

.github/workflows/ansible-integration-tests.yml
.github/workflows/gcloud.yml
.github/workflows/gcsfuse.yml
CONTRIBUTING.md
molecule/gcloud/archive_playbook.yml
molecule/gcloud/converge.yml
molecule/gcloud/molecule.yml
molecule/gcloud/package_playbook.yml
molecule/gcloud/verify.yml
molecule/gcsfuse/converge.yml
molecule/gcsfuse/molecule.yml
molecule/gcsfuse/verify.yml
roles/gcloud/tasks/archive/archive_install.yml
roles/gcloud/tasks/archive/command_completion.yml
roles/gcloud/tasks/archive/main.yml
roles/gcloud/tasks/main.yml
roles/gcloud/tasks/package/debian.yml
roles/gcloud/tasks/package/main.yml
roles/gcloud/tasks/package/redhat.yml
roles/gcsfuse/tasks/debian.yml
roles/gcsfuse/tasks/main.yml
tests/integration/targets/gcp_compute_node_group/aliases
tests/integration/targets/gcp_compute_region_target_https_proxy/aliases
tests/integration/targets/gcp_resourcemanager_project/aliases
tests/integration/targets/gcp_sql_ssl_cert/aliases

Some test cases are unsupported due to environmental or
blocking code restrictions (e.g. unimplemented dependent resources).
As these will likely not be fixed before the first release certified
for Ansible 2.11 and beyond, documenting them instead.
Ansible role tests were failing due to ansible-lint reporting
multiple errors.
Fixing those errors resolves the failing tests.

fix role tests and document unsupported CI tests

---

.github/workflows/ansible-integration-tests.yml
.github/workflows/ansible-test.yml
.vscode/settings.json
CHANGELOG.rst
CONTRIBUTING.md
MAINTAINING.md
changelogs/.plugin-cache.yaml
changelogs/changelog.yaml
changelogs/config.yaml
changelogs/fragments/0001_disk.yml
galaxy.yml
meta/runtime.yml
requirements-test.txt
tests/integration/targets/gcp_spanner_database/tasks/autogen.yml

- Updating and documenting changelog creation process. antsibull-changelog was chosen because it is the standard tooling recommended by Ansible developers.
- Documenting the release process and several others so others can perform it in the future.
- Updating the integration tests to test against 2.13, which the 1.1.0 final release will be certified for.
- Created changelog and update galaxy.yaml for 1.1.0-beta, which will be the next release.

prepping for 1.1.0-beta release

---

.github/workflows/ansible-integration-tests.yml

The integration test filter syntax was restrictive and disabled running them on push.

tests: fix integration tests not running on push

---

.github/workflows/ansible-integration-tests.yml

the previous fix had invalid syntax (hard to test against the
master branch until after push).
This syntax is documented as correct:
https://github.com/actions/runner/issues/950

tests: fix integration tests 2 

---

.github/workflows/ansible-test.yml
molecule/gcloud/archive_playbook.yml
molecule/gcloud/converge.yml
molecule/gcloud/package_playbook.yml
molecule/gcsfuse/converge.yml
roles/gcloud/tasks/archive/archive_install.yml
roles/gcloud/tasks/archive/command_completion.yml
roles/gcloud/tasks/archive/main.yml
roles/gcloud/tasks/main.yml
roles/gcloud/tasks/package/debian.yml
roles/gcloud/tasks/package/main.yml
roles/gcloud/tasks/package/redhat.yml
roles/gcsfuse/meta/main.yml
roles/gcsfuse/tasks/debian.yml
roles/gcsfuse/tasks/main.yml

Ansible-lint is required for Ansible collection
certification for Automation Hub.
gcsfuse had no metadata associated with it, failing the Ansible Hub upload.

fixing ansible-lint errors, fix gcsfuse

---

.github/workflows/ansible-test.yml
CHANGELOG.rst
changelogs/.plugin-cache.yaml
changelogs/changelog.yaml
galaxy.yml
plugins/module_utils/gcp_utils.py

Automation Hub still runs sanity tests on python 2.7
updating release to 1.1.1 to publish a new version.

tests: add sanity tests for python 2.7

---

CHANGELOG.rst
changelogs/.plugin-cache.yaml
changelogs/changelog.yaml
galaxy.yml
plugins/inventory/gcp_compute.py

commit ccbde5f93e76404a5165a675a38cf2e1b83b4794 introduced a backwards-incompatible change which made ansible-inventory no longer recognize `gcp_compute` as a valid package name.
This would break users who are use `gcp_compute` (instead of the new `google.cloud.gcp_compute`). Accepting both until at least a major version change.
fixes #536.

re-add gcp_compute as a valid plugin name

---

.gitignore
plugins/module_utils/gcp_utils.py

Fixes ansible-collections/google.cloud#538.
* When the `auth_type` is "serviceaccount", but neither `service_account_file` or `service_account_contents` are set, an error message clearly stating this will be issues, instead of a misleading "not implemented" error.
* When service account contents fail to parse as JSON, a hint is now given as to why that happened.
* Instead of checking if a service account file doesn't exist, but propagating all other file read errors unhandled, we now check for _all_ `OSError`s that can be generated by the underlying call to `io.open` and indicate what happened.
`gcp_utils.py`

Improve error handling for auth_kind serviceaccount

---

plugins/inventory/gcp_compute.py

Update the example inventory filter to not use a machineType filter. The existing machineType filter example is erroneous, see
https://github.com/ansible-collections/google.cloud/issues/421#issuecomment-1361680826 Change the filter to use "status = RUNNING"
Seeing a broken reference examples in the documentation is very confusing to users.
gcp_compute_inventory docs

Update example inventory filter

---

.github/workflows/ansible-test.yml
.github/workflows/gcloud.yml
.github/workflows/gcsfuse.yml
roles/gcloud/tasks/archive/archive_install.yml
roles/gcloud/tasks/archive/command_completion.yml
roles/gcloud/tasks/archive/main.yml
roles/gcloud/tasks/main.yml
roles/gcloud/tasks/package/debian.yml
roles/gcloud/tasks/package/main.yml
roles/gcloud/tasks/package/redhat.yml
roles/gcsfuse/tasks/debian.yml

ansible-lint was updated and the GitHub
action did not pin the dependency, resulting
in the repository to fail sanity tests.
Updating the repository to adhere to new fatal
linter rules, but also pinning the linter to
prevent failures that may be unrelated to the
particular commit.

chore: pin ansible-lint to 6.13.1

---

plugins/inventory/gcp_compute.py

The version_added field is documented for a very small set of fields, specifically in gcp_compute today.
Removing these values as they are specifying the ansible-core version which is confusing for those who are installing via ansible-galaxy, and the value is not set for any other module.
fixes #550.

fix: remove version_added in gcp_compute

---

changelogs/fragments/gce-changelog.yaml
plugins/modules/gcp_compute_instance_info.py

The link for filter documentation was pointing to
gcloud, which isn't correct as gcp_compute_instance_info communicates with the API.
fixes #549

fix: correct gcp_compute_instance_info filter docs

---

tests/integration/targets/gcp_bigtable_instance/aliases

The test is still flakey currently. A few attempts have been made to fix it, but it seems that the bigtable API does not consistently return the resource after is has been created.
While exploring ways to make it more robust, disabling the test to keep the CI tests from being unreliable to the point of useless.

test: disable gcp_bigtable_instance test

---

tests/integration/targets/gcp_spanner_database/aliases

The test continually fails due to an existing database being created, hich implies the GET isn't returning the proper response.

test: disable flakey spanner test

---

galaxy.yml
plugins/modules/gcp_container_cluster.py

Address Issue #566 
In order to be able to create an IPV6 enabled GKE cluster, you need to specify a custom network + subnetwork which is already exposed.  The other requirements are 
1. stack_type needs to be set to IPV4_IPV6 
2. the data_provider to ADVANCED_DATAPATH.
Example yaml
```yaml
- name: create cluster
gcp_container_cluster:
ip_allocation_policy:
stack_type: "IPV4_IPV6"
network_config:
datapath_provider: "ADVANCED_DATAPATH"
```
gcp_container_cluster

Updating gcp_container_cluster.py, adding support for ip_allocation_policy->stack_type and network_config->datapath_provider

---

plugins/module_utils/gcp_utils.py

`service_account_email` defaults to None if one
is not set. For gcp_compute_instance_info, this results in an invalid request as the service account is populated directly in the path.
Populating `default` when a value is not set fixes the error.
fixes #568

[draft] fix: use default service account if unset

---

plugins/modules/gcp_iam_service_account_key.py

Update docs to explain that the json secret key must not already exist, or the module will try to read it.
fixes #370

fix: iam service account key path must not exist

---

plugins/inventory/gcp_compute.py

Fixes grammatical typo in [google.cloud.gcp_compute inventory documentation](https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_compute_inventory.html) 
Google Cloud Compute Engine inventory plugin

Fix grammatical typo in google.cloud.gcp_compute inventory documentation

---

plugins/inventory/gcp_compute.py

If there is an instance in the inventory without any labels, the labels key won't be present in `self.json`
google.cloud
This will happen under the following conditions:
- labels are set to be used first for the hostname like this: `hostnames: ['labels.ansible_deploy_name', 'name', 'private_ip']`
- an instance exists in your inventory without any labels
Here is an example of the error you get when doing a `ansible-inventory --graph -i gcp_compute.yml`
```
[WARNING]:  * Failed to parse /Users/jarv/workspace/gl-infra/deployer/deploy-tooling/gcp_compute.yml with
ansible_collections.google.cloud.plugins.inventory.gcp_compute plugin: 'labels'
File "/Users/jarv/.local/share/virtualenvs/deploy-tooling-qAV_wwNo/lib/python3.7/site-packages/ansible/inventory/manager.py", line …
```

fix: check for labels in json dict when using them for hostnames

---

scripts/cleanup-project.sh

When the `scripts/cleanup-project.sh` calls `cleanup_resource()` with an empty value for either `$extra_list_arg` or `$extra_delete_arg` it will in turn call `gcloud` with the empty argument, which gets misinterpreted.
For instance, the script cleans up target http proxies with:
```
cleanup_resource "compute" "target-http-proxies" "" "--global"
```
The empty list argument is quoted in the call to `gcloud` (as it should be!), which means that the arguments that `gcloud` processes are `['gcloud', 'compute', 'target-http-proxies', 'list', '--project="blahblah"', '--format="csv[no-heading](name)"', '']`
That last empty string argument is the reason for these log messages:
```
WARNING: Argument `NAME` is deprecated. Use `--filter="name=( 'NAME' ... )"` instead.
```
And it's the reason that the …

fix: don't send empty arguments to gcloud in the cleanup script

---

scripts/cleanup-project.sh

The warnings were:
```
ERROR: Found 3 shellcheck issue(s) which need to be resolved:
ERROR: scripts/cleanup-project.sh:45:21: SC2207: Prefer mapfile or read -a to split command output (or quote to avoid splitting).
ERROR: scripts/cleanup-project.sh:47:21: SC2207: Prefer mapfile or read -a to split command output (or quote to avoid splitting).
ERROR: scripts/cleanup-project.sh:50:24: SC2128: Expanding an array without an index only gives the first element.
```

chore: address cleanup script linter warnings

---

.github/workflows/ansible-integration-tests.yml
.github/workflows/ansible-test.yml
.github/workflows/automationhub.yml
.github/workflows/gcloud.yml
.github/workflows/gcsfuse.yml
.github/workflows/pythonpublish.yml
CONTRIBUTING.md
molecule/gcloud/molecule.yml
molecule/gcsfuse/molecule.yml
roles/gcsfuse/tasks/debian.yml

We're not using any new features from these actions, but the old versions are built on deprecated NodeJS releases.

chore: update GitHub actions to their latest versions

---

tests/integration/targets/gcp_sql_database/tasks/autogen.yml

For MySQL 8.x "utf8" really mean "utf8mb3" and when you request `utf8` as the `charset`, `utf8mb3` is what's returned. Thanks to that, instead of being a no-op the "create a database that already exists" test attempts to update the database and fails rather than seeing that the database exists and is in the correct configuration. The fix here is to use a valid character set (`utf8mb4 ` is the [recommended encoding](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-sets.html)).

chore: fix gcp_sql_database integration test

---

.gitignore
README.md

Missed this one when doing the v1.3.0 upgrade work - saw it *after* I released it to [Ansible Galaxy](https://galaxy.ansible.com/ui/repo/published/google/cloud/) :-(
Also added `ansible.cfg` to `.gitignore` while I'm here.

chore: update README version

---

.github/workflows/ansible-test.yml

This reintroduces the `roles/google_cloud_ops_agents` submodule that was unintentionally removed in #529. This also updates the role to the latest release, [1.0.7](https://github.com/GoogleCloudPlatform/google-cloud-ops-agents-ansible/releases/tag/1.0.7).
- Bug fix
google_cloud_ops_agents role
N/A

Update roles/google_cloud_ops_agents submodule to 1.0.7.

---

plugins/lookup/gcp_secret_manager.py
plugins/modules/gcp_secret_manager.py

Add support for Google Secret Manager as both a module and lookup plugin.  Fixes #543 
gcp_secret_manager
Basic support for GCP secret manager with some testing
```paste below
```

Adding support for Google Secret Manager for issue 543

---

.github/workflows/ansible-integration-tests.yml
.github/workflows/ansible-test.yml
.github/workflows/gcloud.yml
.github/workflows/gcsfuse.yml
README.md
meta/runtime.yml

Also:
- Modify GitHub workflows to run unit tests and lint using all supported Python versions (3.10, 3.11, and 3.12 as of now)
- Drop testing with Python 2.7 as it's no longer supported or required
- Run integration tests with Python 3.10
- ~~Use the [run-ansible-lint](https://github.com/marketplace/actions/run-ansible-lint) GitHub action rather than installing directly~~ The action [doesn't work when running outside of the root workspace directory](https://github.com/ansible/ansible-lint/issues/3938).
This is one of multiple PRs to perform the upgrade; it fixes some issues but adds new issues (new linter errors due to a newer version of `ansible-lint` and broken role tests, to name a couple).

Bump min Ansible version to 2.16

---

plugins/lookup/gcp_secret_manager.py
plugins/modules/gcp_secret_manager.py

The `gcp_secret_manager` module and `gcp_secret_manager` lookup do not support more than 10 secrets versions when you try to get the latest version. The problem is that it sorts the paths before getting the version, so somepath/12 is smaller than somepath/9, so it always returns 9 as the latest version.
gcp_secret_manager
The following steps expose the issue:
* Create a secret
* Add 10 or more versions
* get the latest versions with the module or the lookup
The following script create a test case with both issues.
```shell
#!/usr/bin/env bash
gcloud secrets create test-10-versions --replication-policy="automatic"
for i in {1..10}
do
echo "Secret version $i" > ./file.txt
gcloud secrets versions add test-10-versions --data-file="${PWD}/file.txt"
done
rm ./file.txt
cat …
```

fix: support more than 10 secrets versions on gcp_secret_manager

---

changelogs/gcp_pubsub_subscription_gcs_feature.yaml
plugins/modules/gcp_pubsub_subscription.py
scripts/bootstrap-project.sh
tests/integration/targets/gcp_pubsub_subscription/tasks/autogen.yml

https://github.com/ansible-collections/google.cloud/issues/657
gcp_pubsub_subscription
```paste below
```

https://github.com/ansible-collections/google.cloud/issues/657

---

changelogs/fragments/fix-bigquery-table-create-clustering.yml
plugins/modules/gcp_bigquery_table.py

BigQuery table with clustering creation returns error
Fixes #620 
gcp_bigquery_table
The BigQuery API expects the clustering parameters to be sent with this format: 
```
{
"clustering": {
"fields": ["field1", "field2"]
}
}
```
They are currently being sent in this format (no fields):  
```
{
"clustering": ["field1", "field2"]
}
```

fix: google.cloud.gcp_bigquery_table clustering fields

---

plugins/inventory/gcp_compute.py

The code to process the reponses was not indented correctly so it would only process the last projects response.
Fixes #651
plugins/inventory/gcp_compute.py
This issue only shows up with mutliple projects and retrieve_image_info = true

Fix get_project_disks to process all responses

---

plugins/inventory/gcp_compute.py
tests/integration/targets/inventory_gce/aliases
tests/integration/targets/inventory_gce/playbooks/setup.yml
tests/integration/targets/inventory_gce/playbooks/teardown.yml
tests/integration/targets/inventory_gce/playbooks/test.yml
tests/integration/targets/inventory_gce/playbooks/testcase_basic.yml
tests/integration/targets/inventory_gce/playbooks/testcase_hostname.yml
tests/integration/targets/inventory_gce/playbooks/vars.yml
tests/integration/targets/inventory_gce/runme.sh
tests/integration/targets/inventory_gce/templates/inventory.yml.j2
tests/integration/targets/inventory_gce/test.gcp_compute.yml

Fixes #434
It is basically the same as #438 but with a few extra checks.
plugins/inventory/gcp_compute.py

Adding hostname support to dynamic inventory

---

plugins/lookup/gcp_parameter_manager.py
plugins/modules/gcp_parameter_manager.py
tests/integration/targets/gcp_parameter_manager/aliases
tests/integration/targets/gcp_parameter_manager/defaults/main.yml
tests/integration/targets/gcp_parameter_manager/tasks/main.yml
tests/integration/targets/gcp_parameter_manager/tasks/parameters.yml
tests/integration/targets/gcp_parameter_manager/tasks/parameterslookup.yml
tests/integration/targets/gcp_parameter_manager/tasks/regionalparameters.yml
tests/integration/targets/gcp_parameter_manager/tasks/regionalparameterslookup.yml

Added support for the Parameter Manager through both Ansible module and lookup functionality.
*Module*
Support for creating global and regional parameters
- Create parameter and parameter versions
- Add, update, and delete parameter versions
- Delete parameter
*Lookup*
- Support for retrieving and rendering global and regional parameter versions
- gcp_parameter_manager

feat(parametermanager): added support for parameter manager module and lookup

---

.github/workflows/ansible-integration-tests.yml
.github/workflows/ansible-test.yml

Fixes #680
I think it's about time to start testing with ansible-core 2.19.
.github/workflows/ansible-integration-tests.yml
.github/workflows/ansible-test.yml
https://forum.ansible.com/t/8609/13

Test with ansible-core 2.19

---

plugins/modules/gcp_compute_target_https_proxy.py

The documentation on gcp_compute_target_https_proxy is a bit ambiguous in the sense that it should not be a list of strings, but a list of objects (dicts)
Fixes #673 
plugins/modules/gcp_compute_target_https_proxy

docs: Clarify the type of item expected in ssl_certificates

---

.github/workflows/stale.yaml

Seems to be working now. For instance, #669 "should not be stale based on the last update date the 22-02-2025" and #664 "should be stale based on the last update date the 13-12-2024"

Enable the stale issue workflow

---

plugins/lookup/gcp_secret_manager.py

Problem is discribed in #697
lookup google.cloud.gcp_secret_manager
Before the module didnt apply service_account_contents because it was wrongly named service_account_info. service_account_info is now an alias for service_account_contents.
It is important to note that the service_account_contents will fall back on the environment variable GCP_SERVICE_ACCOUNT_CONTENTS and not GCP_SERVICE_ACCOUNT_INFO. But in my testing the service account token recived from GCP is too big to be stored in an environment variable leaving the fall back useless. I recommend using something like ansible vault to store the service_account_contents to securely retrive the value.
```yml
---
- name: Get a secret from GCP
hosts: localhost
gather_facts: false
vars:
service_account: …
```

Fix improper names for service_account_contents
